<?php View::content(); ?>
<?php echo form_tag('usuario/change_pass/') ?>

<body link="#3191F7" vlink="#3191F7" alink="#3191F7">
<table width="100%">
	<tr>
		<td>
			<h2><?php echo link_to(array("", 'Inicio')) ?> > 
			<?php if(Session::get("userName")=='admin') echo link_to(array("catalogo", 'Cat&aacute;logo'))?>
			<?php if(Session::get("userName")!='admin') echo link_to(array("usuario", 'Cat&aacute;logo'))?> > Cambiar password</h2>
		</td>
		<td align="right">
			<?php if(Auth::is_valid()){?>
			<h3>Usted ha iniciado sesi&oacute;n como: <?php echo link_to(array("usuario/edit/$user->id/", "$user->nombre")) ?>-
			<?php echo link_to("login/logout",'Cerrar sesi&oacute;n'); ?></h3>
			<?php }
			else{?>
			<h3>Usted no ha iniciado sesi&oacute;n<?php }?></h3>
		</td>
	</tr>
	</table>
<?php echo link_to("usuario/edit/$user->id",'Atr&aacute;s','title: Regresar al catalogo',"class: button", "style: display:block; float:none; width:20%; clear:both; margin:2em 2em 2em 0;"); ?>
<font size="4">Los campos marcados con (*) son obligatorios</font><br/>
<table width="40%" cellpadding="4">
    <tr>
        <td><font size="4">(*)Password actual</td></font>
        <td><?php echo password_field_tag("pass") ?></td>
		<?php echo hidden_field_tag(array('usuario.password')) ?>
    </tr>
	<tr>
        <td><font size="4">(*)Nuevo password</td></font>
        <td><?php echo password_field_tag("Npass") ?></td>
    </tr>
	<tr>
        <td><font size="4">(*)Confirmar password</td></font>
        <td><?php echo password_field_tag("NNpass") ?></td>
    </tr>
    <tr>
        
        <?php echo hidden_field_tag(array('usuario.id')) ?>
		<?php echo hidden_field_tag(array('usuario.nombre')) ?>
		<?php echo hidden_field_tag(array('usuario.apellido')) ?>
        <?php echo hidden_field_tag(array('usuario.correo')) ?>
		<?php echo hidden_field_tag(array('usuario.login')) ?>
        <td><?php echo submit_tag('Actualizar') ?></td>
		<?php echo end_form_tag() ?>
		<td><?php //echo link_to("usuario/edit/$user->id", 'Cancelar',"class: button", "style: display:block; float:none; width:50%; clear:both; margin:2em 2em 1em 0;"); ?></td>
    </tr>
</table>

