<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
	<title>Version Beta Venta de Libros</title>
	<?php echo stylesheet_link_tag('style') ?>
	<?php echo stylesheet_link_tags(); ?>
</head>

<body bottommargin="0" leftmargin="0" rightmargin="0" topmargin="0" background="img/background.jpg">

<table height="123" width="100%" cellpadding="0" cellspacing="0" border="0">
<tr valign="top">
<!----- insert logo below ------------------------------------------>
<td><img src="img/templogo.jpg" width="587" height="123" border="0" alt=""></td>
<!------------------------------------------------------------------>
<td width="100%" background="img/topbg.jpg">&nbsp;</td>
</tr>
</table>

<table height="40" width="100%" cellpadding="0" cellspacing="0" border="0">
<tr valign="top">
<td width="100%" background="img/topbar.jpg">&nbsp;</td>
</tr>
</table>

<table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr valign="top">

<td width="201"><br/>
<!----- menu, insert links below ------------------------------------------>
&nbsp;&nbsp;&raquo;&nbsp;<a href="http://www.unicauca.edu.co">En construccion</a><BR>
<img src="img/menubar.jpg" width="201" height="11" border="0" alt=""><BR>
&nbsp;&nbsp;&raquo;&nbsp;<a href="http://www.unicauca.edu.co">En construccion</a><BR>
<img src="img/menubar.jpg" width="201" height="11" border="0" alt=""><BR>
&nbsp;&nbsp;&raquo;&nbsp;<a href="http://www.unicauca.edu.co">En construccion</a><BR>
<img src="img/menubar.jpg" width="201" height="11" border="0" alt=""><BR>
&nbsp;&nbsp;&raquo;&nbsp;<a href="http://www.unicauca.edu.co">En construccion</a><BR>
<img src="img/menubar.jpg" width="201" height="11" border="0" alt=""><BR>
<!-------------------------------------------------------------------------->
</td>

<td width="100%">
	<table width="100%" cellpadding="10" cellspacing="0" border="0">
		<tr valign="top">
			<td>
<!----- content, insert text and content below ------------------------------------------>

    <p></p>
        <?php View::content(); ?>
	<br><br><br><br><br><br><br><br>
<!--------------------------------------------------------------------------------------->



<p align="center">
<!--This site is &copy; Copyright YourName 2004-2005, All Rights Reserved<BR>
<a href="http://www.steves-templates.com" title="Free website templates" class="style2">Free website templates</a></p>-->
			</td>
		</tr>
	</table>
</td>

</tr>
</table>

</body>
</html>

