<?php View::content(); ?>
<html>
<h2> Acerca de TIENDA VIRTUAL </h2>
<font size="4">
<p>TIENDA VIRTUAL es un sistema web creado en 2012 cuyo objeto es la comercializaci&oacute;n ON-LINE 
(en l&iacute;nea) de libros.</p>

Nuestra tienda re&uacute;ne la mejor recopilaci&oacute;n de libros en un mismo sitio, 
ofreciendo la mejor informaci&oacute;n y detalle de cada uno de ellos, 
facilitando as&iacute la comparaci&oacute;n entre las diferentes alternativas. Contamos con uno de 
los mayores portafolios ofrecidos en la red.
Nos esforzamos d&iacute;a a d&iacute;a en mejorar los servicios que prestamos a nuestros visitantes 
para que cada entrada a nuestra aplicaci&oacute;n sea una consulta exitosa que logre satisfacer las 
expectativas generadas. </font><br/><br/><br/>

<font>Informaci&oacute;n adicional</font>
   <p> * Tienda virtual es un software para la compra y venta de libros por internet<br/>
    * Est&aacute; licenciado bajo licencia GPL. Una copia de este software lo puede descargar aqu&iacute;<br/>
    * Realizado por:<br/>
      =>Cristian Ledesma<br/>
      =>Deiber Gaviria<br/>
      =>Rodrigo Ching&aacute;l<br/>
	  =>Mauricio Santacruz<br/>
	</p>

<p>Requerimientos del servidor<br/>
    * Servidor web Apache con soporte para php5<br/>
    * Motor de bases de Datos: Postgresql o MySQL<br/>
    <br/>
</p>
</html>