<?php View::content(); ?>
<html>
<h2> Misi&oacute;n </h2>
<font size="4">
<p>
Establecer inmejorables relaciones comerciales con nuestros compradores y proveedores, 
satisfaciendo los requerimientos de los participantes en cada etapa del proceso comercial, 
brindando asistencia, soporte y eficiente, basados en excelentes herramientas tecnol&oacute;gicas,
 infraestructura y mejora continua de nuestra Organizaci&oacute;n.</p>

<p>El respeto, la honestidad y la responsabilidad son nuestros pilares, y todas 
las actividades est&aacute;n fundamentadas en la aplicaci&oacute;n de la &eacute;tica y las normas legales.</p>

</html>